### ISSUE TITLE
Links to http://fairsharing.org/fso/ terminology broken

### ISSUE THREAD

**Issue by strupp-a** [terms4fairskills/FAIRterminology#1]
Dear all,

is this project still actively maintained? I wondered why the hyperlinks to FAIRsharing are all broken (404 server response). Best, Annika

**Comment by allysonlister** [comment]
This project is actively being maintained and developed. Which links to FAIRsharing are not working? I would be very happy to help in any way I can.

Thanks!

**Comment by allysonlister** [comment]
Please note that the IRIs have recently changed as a result of our OBO Foundry submission, and class IRIs are in the OBO Foundry format now. If you let me know what version of the ontology you are currently using, I can help you with what you might need.

**Comment by strupp-a** [comment]
Thanks a lot for the swift reply, I was looking into v3-Jan2021

**Comment by allysonlister** [comment]
Thanks! We have indeed updated our class IRIs since then. You have two options at the moment:

1. The [latest version of the ontology prior to submission to the OBO Foundry](https://github.com/terms4fairskills/FAIRterminology/blob/master/development/t4fs.owl): this is in the development/ directory of the master branch
2. The current "bleeding edge" version (last updated this morning) in the obo-foundry-updates branch, where we're doing a variety of cleaning, and where the IRIs are of the type requested by the OBO Foundry, e.g. http://purl.obolibrary.org/obo/T4FS_0000012 . Please note that these IRIs will only be resolvable if our OBO Foundry submission is accepted, and it is currently under review. (Please see https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1520 for more information).

Of course, you can carry on using the January 2021 version, but we suggest choosing one of these later versions. We're aiming to have the updates for the foundry submission done this month - our team is run by volunteers and we have been quite busy on other projects, but we have lots of things planned for T4FS, so please let us know how you use it, and if you have any additional questions!

**Comment by strupp-a** [comment]
Thanks again! I am watching activities on https://github.com/terms4fairskills/terms4FAIRskills.github.io now to stay up-to-date on T4FS development
