### ISSUE TITLE
OLS

### ISSUE THREAD

**Issue by fbacall** [terms4fairskills/FAIRterminology#3]
Are there any plans to add this ontology to the Ontology Lookup Service?

https://www.ebi.ac.uk/ols/index

**Comment by allysonlister** [comment]
Yes there is. We're currently in the process of submitting the ontology to the OBO Foundry, so some aspects of the ontology are in flux (for example, they have asked us to put in OBO purls, even though they won't resolve yet). For that reason, we're holding off on OLS until the submission for the OBO Foundry is complete, so that the version we send to OLS is a little more stable.

Thanks for asking!

**Comment by fbacall** [comment]
Thanks for the rapid response!

Is there any kind of time scale for when this would happen?

**Comment by allysonlister** [comment]
Thanks for asking. You can follow the OBO Foundry submission at https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1520. I don't have a timescale personally, but I am hoping it won't be too long.

**Comment by allysonlister** [comment]
Hi @fbacall - the terminology is now available at OLS via this URL: https://www.ebi.ac.uk/ols/ontologies/t4fs
It is also now an OBO Foundry ontology (https://obofoundry.org/ontology/t4fs)

Thank you for your interest, and let us know if you have any questions :)
